/**
 * @brief Emulates recursion through function sequences.
 */

#ifndef TPL_RECURSE_H_
#define TPL_RECURSE_H_

// MIN_WITH_TWO
#define TPL_MIN_WITH_TWO_256 2
#define TPL_MIN_WITH_TWO_255 2
#define TPL_MIN_WITH_TWO_254 2
#define TPL_MIN_WITH_TWO_253 2
#define TPL_MIN_WITH_TWO_252 2
#define TPL_MIN_WITH_TWO_251 2
#define TPL_MIN_WITH_TWO_250 2
#define TPL_MIN_WITH_TWO_249 2
#define TPL_MIN_WITH_TWO_248 2
#define TPL_MIN_WITH_TWO_247 2
#define TPL_MIN_WITH_TWO_246 2
#define TPL_MIN_WITH_TWO_245 2
#define TPL_MIN_WITH_TWO_244 2
#define TPL_MIN_WITH_TWO_243 2
#define TPL_MIN_WITH_TWO_242 2
#define TPL_MIN_WITH_TWO_241 2
#define TPL_MIN_WITH_TWO_240 2
#define TPL_MIN_WITH_TWO_239 2
#define TPL_MIN_WITH_TWO_238 2
#define TPL_MIN_WITH_TWO_237 2
#define TPL_MIN_WITH_TWO_236 2
#define TPL_MIN_WITH_TWO_235 2
#define TPL_MIN_WITH_TWO_234 2
#define TPL_MIN_WITH_TWO_233 2
#define TPL_MIN_WITH_TWO_232 2
#define TPL_MIN_WITH_TWO_231 2
#define TPL_MIN_WITH_TWO_230 2
#define TPL_MIN_WITH_TWO_229 2
#define TPL_MIN_WITH_TWO_228 2
#define TPL_MIN_WITH_TWO_227 2
#define TPL_MIN_WITH_TWO_226 2
#define TPL_MIN_WITH_TWO_225 2
#define TPL_MIN_WITH_TWO_224 2
#define TPL_MIN_WITH_TWO_223 2
#define TPL_MIN_WITH_TWO_222 2
#define TPL_MIN_WITH_TWO_221 2
#define TPL_MIN_WITH_TWO_220 2
#define TPL_MIN_WITH_TWO_219 2
#define TPL_MIN_WITH_TWO_218 2
#define TPL_MIN_WITH_TWO_217 2
#define TPL_MIN_WITH_TWO_216 2
#define TPL_MIN_WITH_TWO_215 2
#define TPL_MIN_WITH_TWO_214 2
#define TPL_MIN_WITH_TWO_213 2
#define TPL_MIN_WITH_TWO_212 2
#define TPL_MIN_WITH_TWO_211 2
#define TPL_MIN_WITH_TWO_210 2
#define TPL_MIN_WITH_TWO_209 2
#define TPL_MIN_WITH_TWO_208 2
#define TPL_MIN_WITH_TWO_207 2
#define TPL_MIN_WITH_TWO_206 2
#define TPL_MIN_WITH_TWO_205 2
#define TPL_MIN_WITH_TWO_204 2
#define TPL_MIN_WITH_TWO_203 2
#define TPL_MIN_WITH_TWO_202 2
#define TPL_MIN_WITH_TWO_201 2
#define TPL_MIN_WITH_TWO_200 2
#define TPL_MIN_WITH_TWO_199 2
#define TPL_MIN_WITH_TWO_198 2
#define TPL_MIN_WITH_TWO_197 2
#define TPL_MIN_WITH_TWO_196 2
#define TPL_MIN_WITH_TWO_195 2
#define TPL_MIN_WITH_TWO_194 2
#define TPL_MIN_WITH_TWO_193 2
#define TPL_MIN_WITH_TWO_192 2
#define TPL_MIN_WITH_TWO_191 2
#define TPL_MIN_WITH_TWO_190 2
#define TPL_MIN_WITH_TWO_189 2
#define TPL_MIN_WITH_TWO_188 2
#define TPL_MIN_WITH_TWO_187 2
#define TPL_MIN_WITH_TWO_186 2
#define TPL_MIN_WITH_TWO_185 2
#define TPL_MIN_WITH_TWO_184 2
#define TPL_MIN_WITH_TWO_183 2
#define TPL_MIN_WITH_TWO_182 2
#define TPL_MIN_WITH_TWO_181 2
#define TPL_MIN_WITH_TWO_180 2
#define TPL_MIN_WITH_TWO_179 2
#define TPL_MIN_WITH_TWO_178 2
#define TPL_MIN_WITH_TWO_177 2
#define TPL_MIN_WITH_TWO_176 2
#define TPL_MIN_WITH_TWO_175 2
#define TPL_MIN_WITH_TWO_174 2
#define TPL_MIN_WITH_TWO_173 2
#define TPL_MIN_WITH_TWO_172 2
#define TPL_MIN_WITH_TWO_171 2
#define TPL_MIN_WITH_TWO_170 2
#define TPL_MIN_WITH_TWO_169 2
#define TPL_MIN_WITH_TWO_168 2
#define TPL_MIN_WITH_TWO_167 2
#define TPL_MIN_WITH_TWO_166 2
#define TPL_MIN_WITH_TWO_165 2
#define TPL_MIN_WITH_TWO_164 2
#define TPL_MIN_WITH_TWO_163 2
#define TPL_MIN_WITH_TWO_162 2
#define TPL_MIN_WITH_TWO_161 2
#define TPL_MIN_WITH_TWO_160 2
#define TPL_MIN_WITH_TWO_159 2
#define TPL_MIN_WITH_TWO_158 2
#define TPL_MIN_WITH_TWO_157 2
#define TPL_MIN_WITH_TWO_156 2
#define TPL_MIN_WITH_TWO_155 2
#define TPL_MIN_WITH_TWO_154 2
#define TPL_MIN_WITH_TWO_153 2
#define TPL_MIN_WITH_TWO_152 2
#define TPL_MIN_WITH_TWO_151 2
#define TPL_MIN_WITH_TWO_150 2
#define TPL_MIN_WITH_TWO_149 2
#define TPL_MIN_WITH_TWO_148 2
#define TPL_MIN_WITH_TWO_147 2
#define TPL_MIN_WITH_TWO_146 2
#define TPL_MIN_WITH_TWO_145 2
#define TPL_MIN_WITH_TWO_144 2
#define TPL_MIN_WITH_TWO_143 2
#define TPL_MIN_WITH_TWO_142 2
#define TPL_MIN_WITH_TWO_141 2
#define TPL_MIN_WITH_TWO_140 2
#define TPL_MIN_WITH_TWO_139 2
#define TPL_MIN_WITH_TWO_138 2
#define TPL_MIN_WITH_TWO_137 2
#define TPL_MIN_WITH_TWO_136 2
#define TPL_MIN_WITH_TWO_135 2
#define TPL_MIN_WITH_TWO_134 2
#define TPL_MIN_WITH_TWO_133 2
#define TPL_MIN_WITH_TWO_132 2
#define TPL_MIN_WITH_TWO_131 2
#define TPL_MIN_WITH_TWO_130 2
#define TPL_MIN_WITH_TWO_129 2
#define TPL_MIN_WITH_TWO_128 2
#define TPL_MIN_WITH_TWO_127 2
#define TPL_MIN_WITH_TWO_126 2
#define TPL_MIN_WITH_TWO_125 2
#define TPL_MIN_WITH_TWO_124 2
#define TPL_MIN_WITH_TWO_123 2
#define TPL_MIN_WITH_TWO_122 2
#define TPL_MIN_WITH_TWO_121 2
#define TPL_MIN_WITH_TWO_120 2
#define TPL_MIN_WITH_TWO_119 2
#define TPL_MIN_WITH_TWO_118 2
#define TPL_MIN_WITH_TWO_117 2
#define TPL_MIN_WITH_TWO_116 2
#define TPL_MIN_WITH_TWO_115 2
#define TPL_MIN_WITH_TWO_114 2
#define TPL_MIN_WITH_TWO_113 2
#define TPL_MIN_WITH_TWO_112 2
#define TPL_MIN_WITH_TWO_111 2
#define TPL_MIN_WITH_TWO_110 2
#define TPL_MIN_WITH_TWO_109 2
#define TPL_MIN_WITH_TWO_108 2
#define TPL_MIN_WITH_TWO_107 2
#define TPL_MIN_WITH_TWO_106 2
#define TPL_MIN_WITH_TWO_105 2
#define TPL_MIN_WITH_TWO_104 2
#define TPL_MIN_WITH_TWO_103 2
#define TPL_MIN_WITH_TWO_102 2
#define TPL_MIN_WITH_TWO_101 2
#define TPL_MIN_WITH_TWO_100 2
#define TPL_MIN_WITH_TWO_99 2
#define TPL_MIN_WITH_TWO_98 2
#define TPL_MIN_WITH_TWO_97 2
#define TPL_MIN_WITH_TWO_96 2
#define TPL_MIN_WITH_TWO_95 2
#define TPL_MIN_WITH_TWO_94 2
#define TPL_MIN_WITH_TWO_93 2
#define TPL_MIN_WITH_TWO_92 2
#define TPL_MIN_WITH_TWO_91 2
#define TPL_MIN_WITH_TWO_90 2
#define TPL_MIN_WITH_TWO_89 2
#define TPL_MIN_WITH_TWO_88 2
#define TPL_MIN_WITH_TWO_87 2
#define TPL_MIN_WITH_TWO_86 2
#define TPL_MIN_WITH_TWO_85 2
#define TPL_MIN_WITH_TWO_84 2
#define TPL_MIN_WITH_TWO_83 2
#define TPL_MIN_WITH_TWO_82 2
#define TPL_MIN_WITH_TWO_81 2
#define TPL_MIN_WITH_TWO_80 2
#define TPL_MIN_WITH_TWO_79 2
#define TPL_MIN_WITH_TWO_78 2
#define TPL_MIN_WITH_TWO_77 2
#define TPL_MIN_WITH_TWO_76 2
#define TPL_MIN_WITH_TWO_75 2
#define TPL_MIN_WITH_TWO_74 2
#define TPL_MIN_WITH_TWO_73 2
#define TPL_MIN_WITH_TWO_72 2
#define TPL_MIN_WITH_TWO_71 2
#define TPL_MIN_WITH_TWO_70 2
#define TPL_MIN_WITH_TWO_69 2
#define TPL_MIN_WITH_TWO_68 2
#define TPL_MIN_WITH_TWO_67 2
#define TPL_MIN_WITH_TWO_66 2
#define TPL_MIN_WITH_TWO_65 2
#define TPL_MIN_WITH_TWO_64 2
#define TPL_MIN_WITH_TWO_63 2
#define TPL_MIN_WITH_TWO_62 2
#define TPL_MIN_WITH_TWO_61 2
#define TPL_MIN_WITH_TWO_60 2
#define TPL_MIN_WITH_TWO_59 2
#define TPL_MIN_WITH_TWO_58 2
#define TPL_MIN_WITH_TWO_57 2
#define TPL_MIN_WITH_TWO_56 2
#define TPL_MIN_WITH_TWO_55 2
#define TPL_MIN_WITH_TWO_54 2
#define TPL_MIN_WITH_TWO_53 2
#define TPL_MIN_WITH_TWO_52 2
#define TPL_MIN_WITH_TWO_51 2
#define TPL_MIN_WITH_TWO_50 2
#define TPL_MIN_WITH_TWO_49 2
#define TPL_MIN_WITH_TWO_48 2
#define TPL_MIN_WITH_TWO_47 2
#define TPL_MIN_WITH_TWO_46 2
#define TPL_MIN_WITH_TWO_45 2
#define TPL_MIN_WITH_TWO_44 2
#define TPL_MIN_WITH_TWO_43 2
#define TPL_MIN_WITH_TWO_42 2
#define TPL_MIN_WITH_TWO_41 2
#define TPL_MIN_WITH_TWO_40 2
#define TPL_MIN_WITH_TWO_39 2
#define TPL_MIN_WITH_TWO_38 2
#define TPL_MIN_WITH_TWO_37 2
#define TPL_MIN_WITH_TWO_36 2
#define TPL_MIN_WITH_TWO_35 2
#define TPL_MIN_WITH_TWO_34 2
#define TPL_MIN_WITH_TWO_33 2
#define TPL_MIN_WITH_TWO_32 2
#define TPL_MIN_WITH_TWO_31 2
#define TPL_MIN_WITH_TWO_30 2
#define TPL_MIN_WITH_TWO_29 2
#define TPL_MIN_WITH_TWO_28 2
#define TPL_MIN_WITH_TWO_27 2
#define TPL_MIN_WITH_TWO_26 2
#define TPL_MIN_WITH_TWO_25 2
#define TPL_MIN_WITH_TWO_24 2
#define TPL_MIN_WITH_TWO_23 2
#define TPL_MIN_WITH_TWO_22 2
#define TPL_MIN_WITH_TWO_21 2
#define TPL_MIN_WITH_TWO_20 2
#define TPL_MIN_WITH_TWO_19 2
#define TPL_MIN_WITH_TWO_18 2
#define TPL_MIN_WITH_TWO_17 2
#define TPL_MIN_WITH_TWO_16 2
#define TPL_MIN_WITH_TWO_15 2
#define TPL_MIN_WITH_TWO_14 2
#define TPL_MIN_WITH_TWO_13 2
#define TPL_MIN_WITH_TWO_12 2
#define TPL_MIN_WITH_TWO_11 2
#define TPL_MIN_WITH_TWO_10 2
#define TPL_MIN_WITH_TWO_9 2
#define TPL_MIN_WITH_TWO_8 2
#define TPL_MIN_WITH_TWO_7 2
#define TPL_MIN_WITH_TWO_6 2
#define TPL_MIN_WITH_TWO_5 2
#define TPL_MIN_WITH_TWO_4 2
#define TPL_MIN_WITH_TWO_3 2
#define TPL_MIN_WITH_TWO_2 2
#define TPL_MIN_WITH_TWO_1 1
#define TPL_MIN_WITH_TWO_0 0

// RECURSE
#define TPL_RECURSE_256(t, F) F(TPL_RECURSE_255(t, F))
#define TPL_RECURSE_255(t, F) F(TPL_RECURSE_254(t, F))
#define TPL_RECURSE_254(t, F) F(TPL_RECURSE_253(t, F))
#define TPL_RECURSE_253(t, F) F(TPL_RECURSE_252(t, F))
#define TPL_RECURSE_252(t, F) F(TPL_RECURSE_251(t, F))
#define TPL_RECURSE_251(t, F) F(TPL_RECURSE_250(t, F))
#define TPL_RECURSE_250(t, F) F(TPL_RECURSE_249(t, F))
#define TPL_RECURSE_249(t, F) F(TPL_RECURSE_248(t, F))
#define TPL_RECURSE_248(t, F) F(TPL_RECURSE_247(t, F))
#define TPL_RECURSE_247(t, F) F(TPL_RECURSE_246(t, F))
#define TPL_RECURSE_246(t, F) F(TPL_RECURSE_245(t, F))
#define TPL_RECURSE_245(t, F) F(TPL_RECURSE_244(t, F))
#define TPL_RECURSE_244(t, F) F(TPL_RECURSE_243(t, F))
#define TPL_RECURSE_243(t, F) F(TPL_RECURSE_242(t, F))
#define TPL_RECURSE_242(t, F) F(TPL_RECURSE_241(t, F))
#define TPL_RECURSE_241(t, F) F(TPL_RECURSE_240(t, F))
#define TPL_RECURSE_240(t, F) F(TPL_RECURSE_239(t, F))
#define TPL_RECURSE_239(t, F) F(TPL_RECURSE_238(t, F))
#define TPL_RECURSE_238(t, F) F(TPL_RECURSE_237(t, F))
#define TPL_RECURSE_237(t, F) F(TPL_RECURSE_236(t, F))
#define TPL_RECURSE_236(t, F) F(TPL_RECURSE_235(t, F))
#define TPL_RECURSE_235(t, F) F(TPL_RECURSE_234(t, F))
#define TPL_RECURSE_234(t, F) F(TPL_RECURSE_233(t, F))
#define TPL_RECURSE_233(t, F) F(TPL_RECURSE_232(t, F))
#define TPL_RECURSE_232(t, F) F(TPL_RECURSE_231(t, F))
#define TPL_RECURSE_231(t, F) F(TPL_RECURSE_230(t, F))
#define TPL_RECURSE_230(t, F) F(TPL_RECURSE_229(t, F))
#define TPL_RECURSE_229(t, F) F(TPL_RECURSE_228(t, F))
#define TPL_RECURSE_228(t, F) F(TPL_RECURSE_227(t, F))
#define TPL_RECURSE_227(t, F) F(TPL_RECURSE_226(t, F))
#define TPL_RECURSE_226(t, F) F(TPL_RECURSE_225(t, F))
#define TPL_RECURSE_225(t, F) F(TPL_RECURSE_224(t, F))
#define TPL_RECURSE_224(t, F) F(TPL_RECURSE_223(t, F))
#define TPL_RECURSE_223(t, F) F(TPL_RECURSE_222(t, F))
#define TPL_RECURSE_222(t, F) F(TPL_RECURSE_221(t, F))
#define TPL_RECURSE_221(t, F) F(TPL_RECURSE_220(t, F))
#define TPL_RECURSE_220(t, F) F(TPL_RECURSE_219(t, F))
#define TPL_RECURSE_219(t, F) F(TPL_RECURSE_218(t, F))
#define TPL_RECURSE_218(t, F) F(TPL_RECURSE_217(t, F))
#define TPL_RECURSE_217(t, F) F(TPL_RECURSE_216(t, F))
#define TPL_RECURSE_216(t, F) F(TPL_RECURSE_215(t, F))
#define TPL_RECURSE_215(t, F) F(TPL_RECURSE_214(t, F))
#define TPL_RECURSE_214(t, F) F(TPL_RECURSE_213(t, F))
#define TPL_RECURSE_213(t, F) F(TPL_RECURSE_212(t, F))
#define TPL_RECURSE_212(t, F) F(TPL_RECURSE_211(t, F))
#define TPL_RECURSE_211(t, F) F(TPL_RECURSE_210(t, F))
#define TPL_RECURSE_210(t, F) F(TPL_RECURSE_209(t, F))
#define TPL_RECURSE_209(t, F) F(TPL_RECURSE_208(t, F))
#define TPL_RECURSE_208(t, F) F(TPL_RECURSE_207(t, F))
#define TPL_RECURSE_207(t, F) F(TPL_RECURSE_206(t, F))
#define TPL_RECURSE_206(t, F) F(TPL_RECURSE_205(t, F))
#define TPL_RECURSE_205(t, F) F(TPL_RECURSE_204(t, F))
#define TPL_RECURSE_204(t, F) F(TPL_RECURSE_203(t, F))
#define TPL_RECURSE_203(t, F) F(TPL_RECURSE_202(t, F))
#define TPL_RECURSE_202(t, F) F(TPL_RECURSE_201(t, F))
#define TPL_RECURSE_201(t, F) F(TPL_RECURSE_200(t, F))
#define TPL_RECURSE_200(t, F) F(TPL_RECURSE_199(t, F))
#define TPL_RECURSE_199(t, F) F(TPL_RECURSE_198(t, F))
#define TPL_RECURSE_198(t, F) F(TPL_RECURSE_197(t, F))
#define TPL_RECURSE_197(t, F) F(TPL_RECURSE_196(t, F))
#define TPL_RECURSE_196(t, F) F(TPL_RECURSE_195(t, F))
#define TPL_RECURSE_195(t, F) F(TPL_RECURSE_194(t, F))
#define TPL_RECURSE_194(t, F) F(TPL_RECURSE_193(t, F))
#define TPL_RECURSE_193(t, F) F(TPL_RECURSE_192(t, F))
#define TPL_RECURSE_192(t, F) F(TPL_RECURSE_191(t, F))
#define TPL_RECURSE_191(t, F) F(TPL_RECURSE_190(t, F))
#define TPL_RECURSE_190(t, F) F(TPL_RECURSE_189(t, F))
#define TPL_RECURSE_189(t, F) F(TPL_RECURSE_188(t, F))
#define TPL_RECURSE_188(t, F) F(TPL_RECURSE_187(t, F))
#define TPL_RECURSE_187(t, F) F(TPL_RECURSE_186(t, F))
#define TPL_RECURSE_186(t, F) F(TPL_RECURSE_185(t, F))
#define TPL_RECURSE_185(t, F) F(TPL_RECURSE_184(t, F))
#define TPL_RECURSE_184(t, F) F(TPL_RECURSE_183(t, F))
#define TPL_RECURSE_183(t, F) F(TPL_RECURSE_182(t, F))
#define TPL_RECURSE_182(t, F) F(TPL_RECURSE_181(t, F))
#define TPL_RECURSE_181(t, F) F(TPL_RECURSE_180(t, F))
#define TPL_RECURSE_180(t, F) F(TPL_RECURSE_179(t, F))
#define TPL_RECURSE_179(t, F) F(TPL_RECURSE_178(t, F))
#define TPL_RECURSE_178(t, F) F(TPL_RECURSE_177(t, F))
#define TPL_RECURSE_177(t, F) F(TPL_RECURSE_176(t, F))
#define TPL_RECURSE_176(t, F) F(TPL_RECURSE_175(t, F))
#define TPL_RECURSE_175(t, F) F(TPL_RECURSE_174(t, F))
#define TPL_RECURSE_174(t, F) F(TPL_RECURSE_173(t, F))
#define TPL_RECURSE_173(t, F) F(TPL_RECURSE_172(t, F))
#define TPL_RECURSE_172(t, F) F(TPL_RECURSE_171(t, F))
#define TPL_RECURSE_171(t, F) F(TPL_RECURSE_170(t, F))
#define TPL_RECURSE_170(t, F) F(TPL_RECURSE_169(t, F))
#define TPL_RECURSE_169(t, F) F(TPL_RECURSE_168(t, F))
#define TPL_RECURSE_168(t, F) F(TPL_RECURSE_167(t, F))
#define TPL_RECURSE_167(t, F) F(TPL_RECURSE_166(t, F))
#define TPL_RECURSE_166(t, F) F(TPL_RECURSE_165(t, F))
#define TPL_RECURSE_165(t, F) F(TPL_RECURSE_164(t, F))
#define TPL_RECURSE_164(t, F) F(TPL_RECURSE_163(t, F))
#define TPL_RECURSE_163(t, F) F(TPL_RECURSE_162(t, F))
#define TPL_RECURSE_162(t, F) F(TPL_RECURSE_161(t, F))
#define TPL_RECURSE_161(t, F) F(TPL_RECURSE_160(t, F))
#define TPL_RECURSE_160(t, F) F(TPL_RECURSE_159(t, F))
#define TPL_RECURSE_159(t, F) F(TPL_RECURSE_158(t, F))
#define TPL_RECURSE_158(t, F) F(TPL_RECURSE_157(t, F))
#define TPL_RECURSE_157(t, F) F(TPL_RECURSE_156(t, F))
#define TPL_RECURSE_156(t, F) F(TPL_RECURSE_155(t, F))
#define TPL_RECURSE_155(t, F) F(TPL_RECURSE_154(t, F))
#define TPL_RECURSE_154(t, F) F(TPL_RECURSE_153(t, F))
#define TPL_RECURSE_153(t, F) F(TPL_RECURSE_152(t, F))
#define TPL_RECURSE_152(t, F) F(TPL_RECURSE_151(t, F))
#define TPL_RECURSE_151(t, F) F(TPL_RECURSE_150(t, F))
#define TPL_RECURSE_150(t, F) F(TPL_RECURSE_149(t, F))
#define TPL_RECURSE_149(t, F) F(TPL_RECURSE_148(t, F))
#define TPL_RECURSE_148(t, F) F(TPL_RECURSE_147(t, F))
#define TPL_RECURSE_147(t, F) F(TPL_RECURSE_146(t, F))
#define TPL_RECURSE_146(t, F) F(TPL_RECURSE_145(t, F))
#define TPL_RECURSE_145(t, F) F(TPL_RECURSE_144(t, F))
#define TPL_RECURSE_144(t, F) F(TPL_RECURSE_143(t, F))
#define TPL_RECURSE_143(t, F) F(TPL_RECURSE_142(t, F))
#define TPL_RECURSE_142(t, F) F(TPL_RECURSE_141(t, F))
#define TPL_RECURSE_141(t, F) F(TPL_RECURSE_140(t, F))
#define TPL_RECURSE_140(t, F) F(TPL_RECURSE_139(t, F))
#define TPL_RECURSE_139(t, F) F(TPL_RECURSE_138(t, F))
#define TPL_RECURSE_138(t, F) F(TPL_RECURSE_137(t, F))
#define TPL_RECURSE_137(t, F) F(TPL_RECURSE_136(t, F))
#define TPL_RECURSE_136(t, F) F(TPL_RECURSE_135(t, F))
#define TPL_RECURSE_135(t, F) F(TPL_RECURSE_134(t, F))
#define TPL_RECURSE_134(t, F) F(TPL_RECURSE_133(t, F))
#define TPL_RECURSE_133(t, F) F(TPL_RECURSE_132(t, F))
#define TPL_RECURSE_132(t, F) F(TPL_RECURSE_131(t, F))
#define TPL_RECURSE_131(t, F) F(TPL_RECURSE_130(t, F))
#define TPL_RECURSE_130(t, F) F(TPL_RECURSE_129(t, F))
#define TPL_RECURSE_129(t, F) F(TPL_RECURSE_128(t, F))
#define TPL_RECURSE_128(t, F) F(TPL_RECURSE_127(t, F))
#define TPL_RECURSE_127(t, F) F(TPL_RECURSE_126(t, F))
#define TPL_RECURSE_126(t, F) F(TPL_RECURSE_125(t, F))
#define TPL_RECURSE_125(t, F) F(TPL_RECURSE_124(t, F))
#define TPL_RECURSE_124(t, F) F(TPL_RECURSE_123(t, F))
#define TPL_RECURSE_123(t, F) F(TPL_RECURSE_122(t, F))
#define TPL_RECURSE_122(t, F) F(TPL_RECURSE_121(t, F))
#define TPL_RECURSE_121(t, F) F(TPL_RECURSE_120(t, F))
#define TPL_RECURSE_120(t, F) F(TPL_RECURSE_119(t, F))
#define TPL_RECURSE_119(t, F) F(TPL_RECURSE_118(t, F))
#define TPL_RECURSE_118(t, F) F(TPL_RECURSE_117(t, F))
#define TPL_RECURSE_117(t, F) F(TPL_RECURSE_116(t, F))
#define TPL_RECURSE_116(t, F) F(TPL_RECURSE_115(t, F))
#define TPL_RECURSE_115(t, F) F(TPL_RECURSE_114(t, F))
#define TPL_RECURSE_114(t, F) F(TPL_RECURSE_113(t, F))
#define TPL_RECURSE_113(t, F) F(TPL_RECURSE_112(t, F))
#define TPL_RECURSE_112(t, F) F(TPL_RECURSE_111(t, F))
#define TPL_RECURSE_111(t, F) F(TPL_RECURSE_110(t, F))
#define TPL_RECURSE_110(t, F) F(TPL_RECURSE_109(t, F))
#define TPL_RECURSE_109(t, F) F(TPL_RECURSE_108(t, F))
#define TPL_RECURSE_108(t, F) F(TPL_RECURSE_107(t, F))
#define TPL_RECURSE_107(t, F) F(TPL_RECURSE_106(t, F))
#define TPL_RECURSE_106(t, F) F(TPL_RECURSE_105(t, F))
#define TPL_RECURSE_105(t, F) F(TPL_RECURSE_104(t, F))
#define TPL_RECURSE_104(t, F) F(TPL_RECURSE_103(t, F))
#define TPL_RECURSE_103(t, F) F(TPL_RECURSE_102(t, F))
#define TPL_RECURSE_102(t, F) F(TPL_RECURSE_101(t, F))
#define TPL_RECURSE_101(t, F) F(TPL_RECURSE_100(t, F))
#define TPL_RECURSE_100(t, F) F(TPL_RECURSE_99(t, F))
#define TPL_RECURSE_99(t, F) F(TPL_RECURSE_98(t, F))
#define TPL_RECURSE_98(t, F) F(TPL_RECURSE_97(t, F))
#define TPL_RECURSE_97(t, F) F(TPL_RECURSE_96(t, F))
#define TPL_RECURSE_96(t, F) F(TPL_RECURSE_95(t, F))
#define TPL_RECURSE_95(t, F) F(TPL_RECURSE_94(t, F))
#define TPL_RECURSE_94(t, F) F(TPL_RECURSE_93(t, F))
#define TPL_RECURSE_93(t, F) F(TPL_RECURSE_92(t, F))
#define TPL_RECURSE_92(t, F) F(TPL_RECURSE_91(t, F))
#define TPL_RECURSE_91(t, F) F(TPL_RECURSE_90(t, F))
#define TPL_RECURSE_90(t, F) F(TPL_RECURSE_89(t, F))
#define TPL_RECURSE_89(t, F) F(TPL_RECURSE_88(t, F))
#define TPL_RECURSE_88(t, F) F(TPL_RECURSE_87(t, F))
#define TPL_RECURSE_87(t, F) F(TPL_RECURSE_86(t, F))
#define TPL_RECURSE_86(t, F) F(TPL_RECURSE_85(t, F))
#define TPL_RECURSE_85(t, F) F(TPL_RECURSE_84(t, F))
#define TPL_RECURSE_84(t, F) F(TPL_RECURSE_83(t, F))
#define TPL_RECURSE_83(t, F) F(TPL_RECURSE_82(t, F))
#define TPL_RECURSE_82(t, F) F(TPL_RECURSE_81(t, F))
#define TPL_RECURSE_81(t, F) F(TPL_RECURSE_80(t, F))
#define TPL_RECURSE_80(t, F) F(TPL_RECURSE_79(t, F))
#define TPL_RECURSE_79(t, F) F(TPL_RECURSE_78(t, F))
#define TPL_RECURSE_78(t, F) F(TPL_RECURSE_77(t, F))
#define TPL_RECURSE_77(t, F) F(TPL_RECURSE_76(t, F))
#define TPL_RECURSE_76(t, F) F(TPL_RECURSE_75(t, F))
#define TPL_RECURSE_75(t, F) F(TPL_RECURSE_74(t, F))
#define TPL_RECURSE_74(t, F) F(TPL_RECURSE_73(t, F))
#define TPL_RECURSE_73(t, F) F(TPL_RECURSE_72(t, F))
#define TPL_RECURSE_72(t, F) F(TPL_RECURSE_71(t, F))
#define TPL_RECURSE_71(t, F) F(TPL_RECURSE_70(t, F))
#define TPL_RECURSE_70(t, F) F(TPL_RECURSE_69(t, F))
#define TPL_RECURSE_69(t, F) F(TPL_RECURSE_68(t, F))
#define TPL_RECURSE_68(t, F) F(TPL_RECURSE_67(t, F))
#define TPL_RECURSE_67(t, F) F(TPL_RECURSE_66(t, F))
#define TPL_RECURSE_66(t, F) F(TPL_RECURSE_65(t, F))
#define TPL_RECURSE_65(t, F) F(TPL_RECURSE_64(t, F))
#define TPL_RECURSE_64(t, F) F(TPL_RECURSE_63(t, F))
#define TPL_RECURSE_63(t, F) F(TPL_RECURSE_62(t, F))
#define TPL_RECURSE_62(t, F) F(TPL_RECURSE_61(t, F))
#define TPL_RECURSE_61(t, F) F(TPL_RECURSE_60(t, F))
#define TPL_RECURSE_60(t, F) F(TPL_RECURSE_59(t, F))
#define TPL_RECURSE_59(t, F) F(TPL_RECURSE_58(t, F))
#define TPL_RECURSE_58(t, F) F(TPL_RECURSE_57(t, F))
#define TPL_RECURSE_57(t, F) F(TPL_RECURSE_56(t, F))
#define TPL_RECURSE_56(t, F) F(TPL_RECURSE_55(t, F))
#define TPL_RECURSE_55(t, F) F(TPL_RECURSE_54(t, F))
#define TPL_RECURSE_54(t, F) F(TPL_RECURSE_53(t, F))
#define TPL_RECURSE_53(t, F) F(TPL_RECURSE_52(t, F))
#define TPL_RECURSE_52(t, F) F(TPL_RECURSE_51(t, F))
#define TPL_RECURSE_51(t, F) F(TPL_RECURSE_50(t, F))
#define TPL_RECURSE_50(t, F) F(TPL_RECURSE_49(t, F))
#define TPL_RECURSE_49(t, F) F(TPL_RECURSE_48(t, F))
#define TPL_RECURSE_48(t, F) F(TPL_RECURSE_47(t, F))
#define TPL_RECURSE_47(t, F) F(TPL_RECURSE_46(t, F))
#define TPL_RECURSE_46(t, F) F(TPL_RECURSE_45(t, F))
#define TPL_RECURSE_45(t, F) F(TPL_RECURSE_44(t, F))
#define TPL_RECURSE_44(t, F) F(TPL_RECURSE_43(t, F))
#define TPL_RECURSE_43(t, F) F(TPL_RECURSE_42(t, F))
#define TPL_RECURSE_42(t, F) F(TPL_RECURSE_41(t, F))
#define TPL_RECURSE_41(t, F) F(TPL_RECURSE_40(t, F))
#define TPL_RECURSE_40(t, F) F(TPL_RECURSE_39(t, F))
#define TPL_RECURSE_39(t, F) F(TPL_RECURSE_38(t, F))
#define TPL_RECURSE_38(t, F) F(TPL_RECURSE_37(t, F))
#define TPL_RECURSE_37(t, F) F(TPL_RECURSE_36(t, F))
#define TPL_RECURSE_36(t, F) F(TPL_RECURSE_35(t, F))
#define TPL_RECURSE_35(t, F) F(TPL_RECURSE_34(t, F))
#define TPL_RECURSE_34(t, F) F(TPL_RECURSE_33(t, F))
#define TPL_RECURSE_33(t, F) F(TPL_RECURSE_32(t, F))
#define TPL_RECURSE_32(t, F) F(TPL_RECURSE_31(t, F))
#define TPL_RECURSE_31(t, F) F(TPL_RECURSE_30(t, F))
#define TPL_RECURSE_30(t, F) F(TPL_RECURSE_29(t, F))
#define TPL_RECURSE_29(t, F) F(TPL_RECURSE_28(t, F))
#define TPL_RECURSE_28(t, F) F(TPL_RECURSE_27(t, F))
#define TPL_RECURSE_27(t, F) F(TPL_RECURSE_26(t, F))
#define TPL_RECURSE_26(t, F) F(TPL_RECURSE_25(t, F))
#define TPL_RECURSE_25(t, F) F(TPL_RECURSE_24(t, F))
#define TPL_RECURSE_24(t, F) F(TPL_RECURSE_23(t, F))
#define TPL_RECURSE_23(t, F) F(TPL_RECURSE_22(t, F))
#define TPL_RECURSE_22(t, F) F(TPL_RECURSE_21(t, F))
#define TPL_RECURSE_21(t, F) F(TPL_RECURSE_20(t, F))
#define TPL_RECURSE_20(t, F) F(TPL_RECURSE_19(t, F))
#define TPL_RECURSE_19(t, F) F(TPL_RECURSE_18(t, F))
#define TPL_RECURSE_18(t, F) F(TPL_RECURSE_17(t, F))
#define TPL_RECURSE_17(t, F) F(TPL_RECURSE_16(t, F))
#define TPL_RECURSE_16(t, F) F(TPL_RECURSE_15(t, F))
#define TPL_RECURSE_15(t, F) F(TPL_RECURSE_14(t, F))
#define TPL_RECURSE_14(t, F) F(TPL_RECURSE_13(t, F))
#define TPL_RECURSE_13(t, F) F(TPL_RECURSE_12(t, F))
#define TPL_RECURSE_12(t, F) F(TPL_RECURSE_11(t, F))
#define TPL_RECURSE_11(t, F) F(TPL_RECURSE_10(t, F))
#define TPL_RECURSE_10(t, F) F(TPL_RECURSE_9(t, F))
#define TPL_RECURSE_9(t, F) F(TPL_RECURSE_8(t, F))
#define TPL_RECURSE_8(t, F) F(TPL_RECURSE_7(t, F))
#define TPL_RECURSE_7(t, F) F(TPL_RECURSE_6(t, F))
#define TPL_RECURSE_6(t, F) F(TPL_RECURSE_5(t, F))
#define TPL_RECURSE_5(t, F) F(TPL_RECURSE_4(t, F))
#define TPL_RECURSE_4(t, F) F(TPL_RECURSE_3(t, F))
#define TPL_RECURSE_3(t, F) F(TPL_RECURSE_2(t, F))
#define TPL_RECURSE_2(t, F) F(TPL_RECURSE_1(t, F))
#define TPL_RECURSE_1(t, F) F(TPL_RECURSE_0(t, F))
#define TPL_RECURSE_0(t, F) t

// FOR_EACH
#define TPL_FOR_EACH_256(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_255(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_255(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_254(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_254(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_253(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_253(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_252(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_252(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_251(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_251(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_250(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_250(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_249(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_249(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_248(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_248(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_247(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_247(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_246(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_246(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_245(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_245(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_244(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_244(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_243(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_243(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_242(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_242(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_241(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_241(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_240(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_240(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_239(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_239(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_238(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_238(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_237(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_237(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_236(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_236(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_235(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_235(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_234(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_234(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_233(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_233(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_232(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_232(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_231(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_231(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_230(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_230(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_229(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_229(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_228(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_228(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_227(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_227(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_226(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_226(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_225(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_225(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_224(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_224(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_223(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_223(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_222(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_222(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_221(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_221(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_220(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_220(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_219(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_219(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_218(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_218(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_217(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_217(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_216(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_216(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_215(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_215(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_214(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_214(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_213(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_213(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_212(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_212(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_211(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_211(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_210(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_210(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_209(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_209(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_208(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_208(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_207(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_207(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_206(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_206(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_205(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_205(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_204(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_204(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_203(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_203(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_202(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_202(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_201(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_201(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_200(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_200(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_199(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_199(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_198(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_198(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_197(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_197(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_196(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_196(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_195(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_195(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_194(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_194(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_193(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_193(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_192(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_192(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_191(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_191(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_190(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_190(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_189(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_189(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_188(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_188(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_187(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_187(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_186(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_186(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_185(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_185(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_184(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_184(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_183(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_183(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_182(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_182(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_181(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_181(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_180(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_180(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_179(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_179(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_178(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_178(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_177(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_177(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_176(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_176(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_175(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_175(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_174(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_174(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_173(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_173(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_172(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_172(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_171(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_171(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_170(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_170(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_169(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_169(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_168(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_168(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_167(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_167(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_166(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_166(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_165(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_165(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_164(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_164(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_163(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_163(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_162(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_162(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_161(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_161(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_160(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_160(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_159(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_159(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_158(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_158(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_157(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_157(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_156(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_156(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_155(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_155(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_154(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_154(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_153(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_153(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_152(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_152(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_151(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_151(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_150(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_150(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_149(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_149(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_148(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_148(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_147(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_147(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_146(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_146(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_145(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_145(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_144(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_144(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_143(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_143(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_142(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_142(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_141(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_141(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_140(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_140(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_139(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_139(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_138(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_138(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_137(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_137(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_136(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_136(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_135(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_135(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_134(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_134(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_133(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_133(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_132(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_132(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_131(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_131(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_130(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_130(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_129(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_129(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_128(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_128(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_127(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_127(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_126(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_126(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_125(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_125(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_124(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_124(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_123(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_123(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_122(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_122(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_121(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_121(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_120(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_120(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_119(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_119(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_118(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_118(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_117(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_117(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_116(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_116(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_115(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_115(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_114(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_114(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_113(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_113(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_112(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_112(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_111(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_111(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_110(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_110(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_109(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_109(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_108(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_108(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_107(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_107(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_106(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_106(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_105(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_105(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_104(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_104(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_103(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_103(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_102(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_102(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_101(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_101(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_100(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_100(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_99(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_99(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_98(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_98(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_97(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_97(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_96(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_96(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_95(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_95(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_94(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_94(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_93(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_93(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_92(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_92(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_91(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_91(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_90(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_90(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_89(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_89(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_88(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_88(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_87(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_87(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_86(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_86(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_85(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_85(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_84(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_84(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_83(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_83(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_82(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_82(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_81(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_81(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_80(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_80(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_79(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_79(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_78(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_78(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_77(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_77(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_76(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_76(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_75(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_75(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_74(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_74(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_73(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_73(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_72(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_72(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_71(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_71(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_70(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_70(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_69(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_69(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_68(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_68(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_67(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_67(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_66(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_66(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_65(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_65(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_64(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_64(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_63(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_63(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_62(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_62(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_61(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_61(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_60(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_60(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_59(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_59(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_58(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_58(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_57(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_57(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_56(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_56(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_55(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_55(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_54(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_54(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_53(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_53(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_52(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_52(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_51(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_51(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_50(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_50(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_49(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_49(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_48(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_48(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_47(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_47(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_46(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_46(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_45(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_45(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_44(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_44(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_43(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_43(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_42(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_42(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_41(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_41(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_40(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_40(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_39(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_39(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_38(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_38(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_37(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_37(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_36(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_36(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_35(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_35(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_34(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_34(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_33(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_33(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_32(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_32(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_31(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_31(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_30(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_30(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_29(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_29(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_28(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_28(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_27(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_27(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_26(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_26(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_25(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_25(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_24(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_24(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_23(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_23(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_22(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_22(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_21(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_21(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_20(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_20(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_19(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_19(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_18(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_18(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_17(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_17(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_16(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_16(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_15(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_15(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_14(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_14(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_13(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_13(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_12(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_12(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_11(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_11(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_10(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_10(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_9(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_9(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_8(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_8(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_7(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_7(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_6(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_6(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_5(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_5(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_4(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_4(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_3(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_3(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_2(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_2(t, F, a) (F(TPL_HEAD(t), a), TPL_TO_LIST(TPL_FOR_EACH_1(TPL_TAIL(t), F, a)))
#define TPL_FOR_EACH_1(t, F, a) (F(TPL_HEAD(t), a))
#define TPL_FOR_EACH_0(t, F, a) ()

// FOR_EACH_S_
#define TPL_FOR_EACH_S_256(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_255(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_255(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_254(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_254(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_253(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_253(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_252(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_252(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_251(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_251(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_250(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_250(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_249(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_249(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_248(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_248(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_247(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_247(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_246(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_246(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_245(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_245(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_244(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_244(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_243(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_243(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_242(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_242(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_241(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_241(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_240(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_240(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_239(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_239(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_238(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_238(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_237(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_237(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_236(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_236(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_235(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_235(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_234(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_234(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_233(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_233(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_232(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_232(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_231(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_231(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_230(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_230(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_229(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_229(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_228(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_228(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_227(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_227(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_226(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_226(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_225(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_225(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_224(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_224(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_223(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_223(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_222(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_222(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_221(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_221(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_220(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_220(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_219(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_219(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_218(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_218(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_217(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_217(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_216(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_216(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_215(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_215(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_214(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_214(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_213(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_213(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_212(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_212(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_211(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_211(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_210(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_210(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_209(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_209(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_208(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_208(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_207(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_207(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_206(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_206(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_205(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_205(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_204(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_204(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_203(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_203(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_202(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_202(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_201(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_201(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_200(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_200(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_199(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_199(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_198(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_198(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_197(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_197(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_196(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_196(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_195(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_195(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_194(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_194(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_193(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_193(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_192(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_192(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_191(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_191(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_190(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_190(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_189(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_189(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_188(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_188(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_187(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_187(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_186(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_186(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_185(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_185(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_184(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_184(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_183(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_183(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_182(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_182(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_181(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_181(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_180(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_180(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_179(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_179(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_178(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_178(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_177(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_177(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_176(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_176(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_175(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_175(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_174(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_174(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_173(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_173(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_172(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_172(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_171(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_171(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_170(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_170(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_169(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_169(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_168(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_168(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_167(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_167(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_166(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_166(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_165(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_165(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_164(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_164(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_163(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_163(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_162(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_162(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_161(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_161(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_160(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_160(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_159(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_159(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_158(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_158(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_157(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_157(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_156(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_156(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_155(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_155(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_154(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_154(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_153(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_153(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_152(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_152(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_151(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_151(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_150(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_150(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_149(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_149(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_148(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_148(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_147(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_147(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_146(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_146(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_145(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_145(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_144(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_144(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_143(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_143(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_142(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_142(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_141(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_141(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_140(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_140(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_139(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_139(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_138(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_138(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_137(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_137(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_136(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_136(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_135(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_135(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_134(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_134(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_133(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_133(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_132(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_132(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_131(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_131(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_130(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_130(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_129(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_129(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_128(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_128(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_127(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_127(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_126(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_126(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_125(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_125(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_124(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_124(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_123(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_123(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_122(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_122(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_121(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_121(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_120(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_120(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_119(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_119(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_118(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_118(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_117(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_117(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_116(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_116(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_115(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_115(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_114(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_114(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_113(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_113(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_112(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_112(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_111(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_111(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_110(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_110(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_109(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_109(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_108(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_108(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_107(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_107(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_106(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_106(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_105(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_105(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_104(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_104(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_103(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_103(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_102(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_102(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_101(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_101(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_100(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_100(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_99(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_99(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_98(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_98(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_97(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_97(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_96(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_96(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_95(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_95(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_94(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_94(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_93(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_93(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_92(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_92(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_91(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_91(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_90(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_90(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_89(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_89(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_88(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_88(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_87(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_87(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_86(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_86(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_85(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_85(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_84(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_84(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_83(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_83(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_82(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_82(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_81(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_81(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_80(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_80(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_79(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_79(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_78(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_78(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_77(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_77(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_76(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_76(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_75(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_75(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_74(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_74(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_73(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_73(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_72(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_72(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_71(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_71(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_70(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_70(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_69(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_69(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_68(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_68(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_67(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_67(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_66(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_66(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_65(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_65(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_64(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_64(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_63(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_63(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_62(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_62(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_61(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_61(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_60(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_60(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_59(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_59(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_58(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_58(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_57(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_57(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_56(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_56(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_55(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_55(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_54(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_54(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_53(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_53(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_52(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_52(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_51(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_51(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_50(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_50(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_49(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_49(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_48(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_48(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_47(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_47(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_46(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_46(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_45(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_45(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_44(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_44(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_43(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_43(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_42(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_42(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_41(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_41(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_40(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_40(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_39(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_39(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_38(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_38(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_37(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_37(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_36(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_36(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_35(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_35(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_34(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_34(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_33(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_33(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_32(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_32(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_31(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_31(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_30(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_30(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_29(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_29(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_28(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_28(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_27(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_27(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_26(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_26(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_25(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_25(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_24(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_24(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_23(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_23(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_22(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_22(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_21(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_21(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_20(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_20(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_19(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_19(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_18(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_18(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_17(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_17(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_16(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_16(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_15(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_15(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_14(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_14(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_13(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_13(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_12(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_12(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_11(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_11(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_10(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_10(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_9(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_9(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_8(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_8(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_7(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_7(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_6(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_6(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_5(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_5(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_4(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_4(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_3(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_3(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_2(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_2(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_1(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_1(t, F, a) F(TPL_HEAD(t), a) TPL_FOR_EACH_S_0(TPL_TAIL(t), F, a)
#define TPL_FOR_EACH_S_0(t, F, ...)

#endif // TPL_RECURSE_H_
